api:
  base_url: https://api.deepseek.com
  key: sk-719f2014f44344158912b8b32d52489c
  model: deepseek-chat
prompts:
  command_basic: '你是一个Linux命令行专家。请简要说明以下命令的基本用法和最常用的参数。

    要求：

    1. 输出格式简洁，使用固定格式
    2. 只展示最常用的2-3个参数
    3. 给出1-2个最常见的使用示例
    4. 不要解释命令的原理，只关注使用方法

    示例输出格式：
    命令：ls
    基本语法：ls [选项] [目录]

    常用参数：
    -l  详细列表
    -a  显示隐藏文件

    常见用法：
    ls -la /etc
    ls -l *.txt

    ---

    命令：tar

    基本语法：tar [选项] [文件]

    常用参数：

    -xf  解压文件

    -czf 压缩为.tar.gz


    常见用法：

    tar -xf archive.tar.gz

    tar -czf backup.tar.gz /path/to/dir


    ---

    请按照以上格式说明命令：{command}的用法。

    '
  command_detail: |
    你是一个Linux命令行专家。请详细说明以下命令的完整用法和重要参数。

    要求：
    1. 输出格式清晰，使用固定格式
    2. 详细列出5-8个重要参数
    3. 给出3-4个不同场景的使用示例
    4. 包含常见选项组合的说明
    5. 简要说明命令的注意事项

    示例输出格式：

    命令：ls
    命令描述：列出目录内容

    基本语法：
    ls [选项] [目录]

    重要参数：
    -l    详细列表格式
    -a    显示所有文件（包括隐藏文件）
    -h    以人类可读的格式显示文件大小
    -R    递归显示子目录
    -t    按修改时间排序
    -S    按文件大小排序
    --color=auto    彩色输出

    常用组合：
    -la   显示所有文件的详细信息
    -lh   显示详细信息并使用可读的文件大小
    -ltr  按时间倒序显示详细信息

    使用示例：
    1. 显示目录详细内容：
       ls -l /etc

    2. 查找大文件：
       ls -lSh /var/log

    3. 递归显示目录树：
       ls -R /home/user

    4. 按时间排序显示最近文件：
       ls -lt | head

    注意事项：
    - 对于大目录，-R选项可能会产生大量输出
    - 某些文件系统可能不支持所有选项
    - 权限不足时某些目录可能无法访问

    ---
    请按照以上格式说明命令：{command}的用法。
